#!/usr/bin/perl
############################################################################
# soepkiptng (c) copyright 2000 Eric Lammerts <eric@lammerts.org>.
# $Id$
############################################################################
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# A copy of the GNU General Public License is available on the World Wide Web
# at `http://www.gnu.org/copyleft/gpl.html'.  You can also obtain it by
# writing to the Free Software Foundation, Inc., 59 Temple Place - Suite 330,
# Boston, MA 02111-1307, USA.
############################################################################

# CONFIG

$configfile = "/etc/soepkiptng.conf";

use DBI;
use Gnome;
init Gnome "soepkiptng.pl";

#init Gnome::Panel::AppletWidget 'soepkiptng.pl';

open F, $configfile or die "$configfile: $!\n";
while(<F>) {
	/^#/ and next;
	s/\s+$//;
	/./ or next;
	if(/^(\w+)\s*=\s*(.*?)\s*$/) {
		$f = $1;
		${$f} = $2;
	} elsif(/^\s+(.*?)\s*$/) {
		# continuation line
		${$f} .= "\n$1";
	} else {
		die "$configfile line $.: invalid format\n";
	}
}
close F;


require "$progdir/soepkiptng.lib";

$dbh = DBI->connect("DBI:$db_type:$db_name:$db_host", $db_user, $db_pass)
	or die "can't connect to database";

$SIG{'HUP'} = sub {
	exec $0;
	die;
};


my $pause_xpm = (
"16 16 4 1",
"       c None s None",
".      c black",
"X      c #808080",
"o      c white",
"                ",
"                ",
"                ",
"                ",
"   ...    ...   ",
"   ...    ...   ",
"   ...    ...   ",
"   ...    ...   ",
"   ...    ...   ",
"   ...    ...   ",
"   ...    ...   ",
"                ",
"                ",
"                ",
"                ",
"                ");

#my $window = new Gtk::Window;
my $window = new Gtk::Widget "GtkWindow",
	type => -toplevel,
	title => "SoepkipTNG status",
	allow_grow => 1,
	allow_shrink => 1,
;

#$window = new Gnome::Panel::AppletWidget 'soepkiptng.pl';
#realize $window;

#my $Label = Gtk::Widget->new("Gnome::CanvasText",
#	text => "A string\nToinen rivi",
#	font_gdk => load Gtk::Gdk::Font('-*-helvetica-*'),
#	fill_color => 'steelblue',
#	anchor => 'center',
#);
      
my $label = new Gtk::Label("Artist\nTitle\nAlbum");
$label->set_justify('left');
#$label->set_usize(300,40);

$button_pause = Gtk::Widget->new("GtkButton",
 -label   => "Pause",
 -border_width => 1,
 -clicked => sub {
	my $pid = get_player_pid();
	if($pid) {
		local *ST;

		open ST,"/proc/$pid/stat" or next;
		$_ = <ST>;
		close ST;
		if(/^\d+\s+\S+\s+(\w)/) {
			if($1 eq "T") {
				kill "CONT", $pid;
			} else {
				kill "STOP", $pid;
			}
		}
	}
  },
  -visible=>1
);

$button_kill = Gtk::Widget->new("GtkButton",
 -label   => "Kill",
 -border_width => 1,
 -clicked => \&kill_song,
 -visible=>1
);


$hbox = new Gtk::HBox 0, 1;
show $hbox;
$window->add($hbox);

$vbox = new Gtk::VBox 0, 1;

$hbox->pack_start($label, 1, 1, 3);
$hbox->pack_start($vbox, 0, 0, 0);

$vbox->pack_start($button_pause, 0, 0, 1);
$vbox->pack_start($button_kill, 0, 0, 1);


#$splashimage = new Gtk::Pixmap($p,$pause_xpm)

update_song();
my $id = Gtk->timeout_add(1000, \&update_song);

$window->signal_connect('destroy', sub { Gtk->exit(0); });

$window->show_all;

Gtk->main;
# Gnome::Panel::AppletWidget;


sub update_song() {
	my $newmtime = (stat $statusfile)[9];

	if($newmtime != $mtime) {
		$mtime = $newmtime;
		if(open F, $statusfile) {
			my $nowplaying;
			chop($nowplaying = <F>);
			close F;

			my $query = "SELECT song.title as title,artist.name as artist,album.name as album,song.id,song.track" .
				 " FROM song,artist,album" .
				 " WHERE song.id=?" .
				 " AND song.artist_id=artist.id AND song.album_id=album.id";
			my $sth = $dbh->prepare($query);
			my $rv = $sth->execute($nowplaying);
			if($now_playing = $sth->fetchrow_hashref) {
				$label->set_text(sprintf("%s\n%s\n[%02d] %s\r",
					$now_playing->{artist},
					$now_playing->{title},
					$now_playing->{track},
					$now_playing->{album}));
			} else {
				$label->set_text("\n\n\n");
			}
		}
	}
	return 1;
};
