#!/usr/bin/perl
############################################################################
# soepkiptng (c) copyright 2000 Eric Lammerts <eric@lammerts.org>.
############################################################################
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License, version 2, as 
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# A copy of the GNU General Public License is available on the World Wide Web
# at `http://www.gnu.org/copyleft/gpl.html'.  You can also obtain it by
# writing to the Free Software Foundation, Inc., 59 Temple Place - Suite 330,
# Boston, MA 02111-1307, USA.
############################################################################

use integer;
use Cwd 'abs_path';
use DBI;
use Socket;
use Getopt::Std;
use POSIX ":sys_wait_h";

# find program directory
$_ = $0;
while(-l) {
	my $l = readlink or die "readlink $_: $!\n";
	if($l =~ m|^/|) { $_ = $l; } else { s|[^/]*$|/$l|; }
}
m|(.*)/|;
my $progdir = abs_path($1);

require "$progdir/soepkiptng.lib";

getopts('avnc:g');

read_configfile(\%conf, $opt_c);

$dbh = DBI->connect("DBI:$conf{db_type}:$conf{db_name}:$conf{db_host}",
	$conf{db_user}, $conf{db_pass}) or die "can't connect to database";

$pid = 0;
open STDOUT, ">/dev/null";
$SIG{CHLD} = sub {
	while(waitpid(-1,WNOHANG) > 0) {
		exit 0 if $@ == 0;
	}
};
for(;;) {
	while((stat $conf{statusfile})[9] == $mtime) { sleep 1; }
	$mtime = (stat _)[9];
	if($pid) { kill 9, $pid; wait; }
	print STDERR "\n"x100;
	open F, $conf{statusfile} or next;
	chop($id = <F>);
	close F;

	($lyrics, $ar, $ti, $al, $tr) = $dbh->selectrow_array(
		"SELECT lyrics.lyrics, artist.name, song.title, album.name, song.track " .
		"FROM song " .
		"LEFT JOIN album ON album.id=song.album_id " .
		"LEFT JOIN artist ON artist.id=song.artist_id " . 
		"LEFT JOIN lyrics ON lyrics.id=song.id " .
		"WHERE song.id=$id");
	$lyrics or next;

	pipe STDIN, STDOUT;
	if(($pid = fork) == 0) {
		open STDOUT, ">/dev/tty";
		exec "less", "-c";
		die "less -c: $!\n";
	}
	close STDIN;
	$t = "$ar - $ti ($al [$tr])";
	print "$t\n";
	print "-" x length($t);
	print "\n\n$lyrics\n";
	close STDOUT;
}
