#!/usr/bin/perl
############################################################################
# soepkiptng (c) copyright 2000 Eric Lammerts <eric@lammerts.org>.
############################################################################
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License, version 2, as 
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# A copy of the GNU General Public License is available on the World Wide Web
# at `http://www.gnu.org/copyleft/gpl.html'.  You can also obtain it by
# writing to the Free Software Foundation, Inc., 59 Temple Place - Suite 330,
# Boston, MA 02111-1307, USA.
############################################################################

use Cwd 'abs_path';
use Getopt::Std;

# find program directory
$_ = $0;
while(-l) {
	my $l = readlink or die "readlink $_: $!\n";
	if($l =~ m|^/|) { $_ = $l; } else { s|[^/]*$|/$l|; }
}
m|(.*)/|;
my $progdir = abs_path($1);

require "$progdir/soepkiptng.lib";

getopts('c:');

read_configfile(\%conf, $opt_c);

$ENV{PATH} = "$progdir/bin:$ENV{PATH}";
use lib "$progdir/lib";

sub add_shout($$) {
	my ($url, $desc) = @_;
	
	my $arid = get_id($dbh, "artist", '') or die;
	my $alid = get_id($dbh, "album", '') or die;
	$dbh->do("REPLACE INTO song SET title=?, filename=?, album_id=?, " .
		"artist_id=?, present=1, encoding=\"Shoutcast\", track=0, " .
		"length=0, time_added=NULL", undef,
		$desc, $url, $alid, $arid) or die;

	warn "Added $url: $desc\n";
	if($have_stream{$url}) { $num_updated++; }
	else { $num_added++; }
}


use DBI;

$dbh = connect_to_db(\%conf);

my $shc = $dbh->selectcol_arrayref("SELECT filename FROM song WHERE filename LIKE \"http:%\"");
foreach(@$shc) {
	$have_stream{$_} = 1;
#	warn "have $_\n";
}

foreach(@ARGV) {
	open F, $_ or do {
		warn "$_: $!\n";
		next;
	};
	my (@url, @title);
	while(<F>) {
		if(/^File(\d+)\s*=\s*(http:\S+)/) {
			$url[$1] = $2;
			next;
		}
		if(/^Title(\d+)\s*=\s*(.*\S+)/) {
			$title[$1] = $2;
			next;
		}
		if(/^(http:\S+)/) {
			add_shout($1, $1);
			next;
		}
	}
	close F;

	for($i = 0; $i < @url; $i++) {
		add_shout($url[$i], $title[$i] || $url[$i])
			if $url[$i];
	}
}

$dbh->disconnect();

printf <<EOF, $num_added, $num_updated;
%4d Shoutcast streams added.
%4d Shoutcast streams updated.
EOF
