#!/usr/bin/perl
############################################################################
# soepkiptng (c) copyright 2000 Eric Lammerts <eric@lammerts.org>.
# $Id$
############################################################################
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# A copy of the GNU General Public License is available on the World Wide Web
# at `http://www.gnu.org/copyleft/gpl.html'.  You can also obtain it by
# writing to the Free Software Foundation, Inc., 59 Temple Place - Suite 330,
# Boston, MA 02111-1307, USA.
############################################################################

# CONFIG

$configfile = "/etc/soepkiptng.conf";

use DBI;

open F, $configfile or die "$configfile: $!\n";
while(<F>) {
	/^#/ and next;
	s/\s+$//;
	/./ or next;
	if(/^(\w+)\s*=\s*(.*?)\s*$/) {
		$f = $1;
		${$f} = $2;
	} elsif(/^\s+(.*?)\s*$/) {
		# continuation line
		${$f} .= "\n$1";
	} else {
		die "$configfile line $.: invalid format\n";
	}
}
close F;

require "$progdir/soepkiptng.lib";

$| = 1;

$dbh = DBI->connect("DBI:$db_type:$db_name:$db_host", $db_user, $db_pass)
	or die "can't connect to database";

$SIG{'HUP'} = sub {
	exec $0;
	die;
};

for(;; sleep 1) {
	$newmtime = (stat $statusfile)[9];
	next if $newmtime == $mtime;
	$mtime = $newmtime;
	if(open F, $statusfile) {
		chop($nowplaying = <F>);
		close F;

		my $query = "SELECT song.title as title,artist.name as artist,album.name as album,song.id,song.track" .
			    " FROM song,artist,album" .
			    " WHERE song.id=?" .
			    " AND song.artist_id=artist.id AND song.album_id=album.id";
		my $sth = $dbh->prepare($query);
		my $rv = $sth->execute($nowplaying);
		if($now_playing = $sth->fetchrow_hashref) {
			printf "\n%s\n%s\n  [%02d] %s\r",
				$now_playing->{artist},
				$now_playing->{title},
				$now_playing->{track},
				$now_playing->{album} or exit;
		} else {
			print "\n\n\n\n" or exit;
		}
	}
}

