#!/usr/bin/perl
############################################################################
# soepkiptng (c) copyright 2000 Eric Lammerts <eric@lammerts.org>.
############################################################################
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License, version 2, as 
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# A copy of the GNU General Public License is available on the World Wide Web
# at `http://www.gnu.org/copyleft/gpl.html'.  You can also obtain it by
# writing to the Free Software Foundation, Inc., 59 Temple Place - Suite 330,
# Boston, MA 02111-1307, USA.
############################################################################

use Cwd 'abs_path';
use DBI;
use Getopt::Std;

# find program directory
$_ = $0;
while(-l) {
	my $l = readlink or die "readlink $_: $!\n";
	if($l =~ m|^/|) { $_ = $l; } else { s|[^/]*$|/$l|; }
}
m|(.*)/|;
my $progdir = abs_path($1);

require "$progdir/soepkiptng.lib";

getopts('c:');

read_configfile(\%conf, $opt_c);

$| = 1;

$dbh = connect_to_db(\%conf);

$SIG{'HUP'} = sub {
	exec $0;
	die;
};

for(;; sleep 1) {
	$newmtime = (stat $conf{statusfile})[9];
	next if $newmtime == $mtime;
	$mtime = $newmtime;
	if(open F, $conf{statusfile}) {
		chop($nowplaying = <F>);
		close F;

		my $query = "SELECT song.title as title,artist.name as artist,album.name as album,song.id,song.track" .
			    " FROM song,artist,album" .
			    " WHERE song.id=?" .
			    " AND song.artist_id=artist.id AND song.album_id=album.id";
		my $sth = $dbh->prepare($query);
		my $rv = $sth->execute($nowplaying);
		if($now_playing = $sth->fetchrow_hashref) {
			printf "\n%s\n%s\n  [%02d] %s\r",
				$now_playing->{artist},
				$now_playing->{title},
				$now_playing->{track},
				$now_playing->{album} or exit;
		} else {
			print "\n\n\n\n" or exit;
		}
	}
}

